;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-indent-line-or-region
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-semi&comma
	c-electric-star
	))
